# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.sonatel: DEBUG

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true

  # Database Configurations
  liquibase:
    contexts: dev, faker
    url: jdbc:mysql://localhost:3307/gateway?useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: passer123

  r2dbc:
    url: r2dbc:mysql://localhost:3307/gateway?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: passer123

  # Email Configurations
  mail:
    host: localhost
    port: 25
    username:
    password:

  messages:
    cache-duration: PT1S

  thymeleaf:
    cache: false

  # Cloud & Gateway Configurations
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/services/service1/**
          filters:
            - StripPrefix=2
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        enabled: true
      enabled: true

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/   # Notez admin:admin ici
  instance:
    appname: gateway
    instanceId: gateway:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    prefer-ip-address: true
server:
  port: 8080
  forward-headers-strategy: native

# JHipster specific properties
jhipster:
  gateway:
    rate-limiting:
      enabled: true
      limit: 100000
      duration-in-seconds: 3600
    authorized-microservices-endpoints:
      service1: /api,/v3/api-docs
      service2: /api,/v3/api-docs
      service3: /api,/v3/api-docs

  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800

  security:
    authentication:
      jwt:
        base64-secret: YTYxMWQ2NmY1YzFmYThmZTliYjBmMzg3NzcxOThjZGQ2YTMwZjU0YzNiMWQ5OGRkMDc5NWViNDgwNjgxYjY2YjNlODZlNjAwMDk5NThlY2Y4NmFjNmMwMWMxOTc4NDQwOTlmMjY0YTQzOGU3MzBiYzQ3M2Y5NTI3MTE4NTE4YjY=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

  mail:
    base-url: http://127.0.0.1:8080

  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
